import { Injectable } from '@angular/core';
import {
  AlignmentType,
  BorderStyle,
  Document,
  Packer,
  Paragraph,
  TextRun
} from 'docx';
import { jsPDF } from 'jspdf';
import {
  CoverLetterDocument,
  ProfessionalResume,
  ResumeEducation,
  ResumeExperience,
  ResumeProject,
  TailoredResult
} from '../models/tailored-result';

@Injectable({ providedIn: 'root' })
export class DownloadService {
  private readonly accentHex = '1F4E78';
  private readonly bodyHex = '1F2937';
  private readonly mutedHex = '5B6573';

  async downloadResumeDocx(result: TailoredResult): Promise<void> {
    const resume = result.resume;
    const document = new Document({
      creator: 'ResumeForge',
      title: `${resume.fullName || 'Candidate'} - Tailored Resume`,
      description: 'ATS-friendly tailored resume generated by ResumeForge.',
      styles: {
        default: {
          document: {
            run: {
              font: 'Aptos',
              size: 20,
              color: this.bodyHex
            },
            paragraph: {
              spacing: { after: 80, line: 240 }
            }
          }
        }
      },
      sections: [
        {
          properties: {
            page: {
              margin: {
                top: 540,
                right: 648,
                bottom: 540,
                left: 648
              }
            }
          },
          children: this.buildResumeDocxContent(resume)
        }
      ]
    });

    const blob = await Packer.toBlob(document);
    this.downloadBlob(blob, `${this.safeFileName(resume.fullName)}-Resume.docx`);
  }

  downloadResumePdf(result: TailoredResult): void {
    const resume = result.resume;
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'pt',
      format: 'letter',
      compress: true
    });

    this.renderResumePdf(pdf, resume);
    pdf.save(`${this.safeFileName(resume.fullName)}-Resume.pdf`);
  }

  async downloadCoverLetterDocx(result: TailoredResult): Promise<void> {
    const resume = result.resume;
    const coverLetter = result.coverLetterDocument;
    const document = new Document({
      creator: 'ResumeForge',
      title: `${resume.fullName || 'Candidate'} - Cover Letter`,
      description: 'Tailored cover letter generated by ResumeForge.',
      styles: {
        default: {
          document: {
            run: {
              font: 'Aptos',
              size: 22,
              color: this.bodyHex
            },
            paragraph: {
              spacing: { after: 180, line: 276 }
            }
          }
        }
      },
      sections: [
        {
          properties: {
            page: {
              margin: {
                top: 720,
                right: 792,
                bottom: 720,
                left: 792
              }
            }
          },
          children: this.buildCoverLetterDocxContent(resume, coverLetter)
        }
      ]
    });

    const blob = await Packer.toBlob(document);
    this.downloadBlob(blob, `${this.safeFileName(resume.fullName)}-Cover-Letter.docx`);
  }

  downloadCoverLetterPdf(result: TailoredResult): void {
    const resume = result.resume;
    const coverLetter = result.coverLetterDocument;
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'pt',
      format: 'letter',
      compress: true
    });

    this.renderCoverLetterPdf(pdf, resume, coverLetter);
    pdf.save(`${this.safeFileName(resume.fullName)}-Cover-Letter.pdf`);
  }

  buildResumePlainText(resume: ProfessionalResume): string {
    const lines: string[] = [];

    if (resume.fullName) {
      lines.push(resume.fullName.toUpperCase());
    }
    if (resume.headline) {
      lines.push(resume.headline);
    }

    const contact = this.contactParts(resume);
    if (contact.length > 0) {
      lines.push(contact.join(' | '));
    }

    lines.push('', 'PROFESSIONAL SUMMARY', resume.summary);

    if (this.cleanStrings(resume.skills).length > 0) {
      lines.push('', 'CORE SKILLS', this.cleanStrings(resume.skills).join(' | '));
    }

    if (resume.experience.length > 0) {
      lines.push('', 'PROFESSIONAL EXPERIENCE');
      for (const experience of resume.experience) {
        lines.push(
          `${experience.jobTitle}${experience.company ? ` | ${experience.company}` : ''}`,
          [experience.location, this.dateRange(experience.startDate, experience.endDate)]
            .filter(Boolean)
            .join(' | '),
          ...this.cleanStrings(experience.bulletPoints).map((point) => `- ${point}`),
          ''
        );
      }
    }

    if (resume.projects.length > 0) {
      lines.push('PROJECTS');
      for (const project of resume.projects) {
        lines.push(
          project.name,
          project.description,
          this.cleanStrings(project.technologies).join(' | '),
          ''
        );
      }
    }

    if (resume.education.length > 0) {
      lines.push('EDUCATION');
      for (const education of resume.education) {
        lines.push(
          education.degree,
          [education.institution, education.location, education.graduationDate]
            .filter(Boolean)
            .join(' | '),
          ...this.cleanStrings(education.details).map((detail) => `- ${detail}`),
          ''
        );
      }
    }

    if (this.cleanStrings(resume.certifications).length > 0) {
      lines.push(
        'CERTIFICATIONS',
        ...this.cleanStrings(resume.certifications).map((certification) => `- ${certification}`)
      );
    }

    return lines.join('\n').replace(/\n{3,}/g, '\n\n').trim();
  }

  buildCoverLetterPlainText(
    resume: ProfessionalResume,
    coverLetter: CoverLetterDocument
  ): string {
    const recipient = coverLetter.recipient.trim() || 'Hiring Manager';
    const company = coverLetter.companyName.trim();
    const role = coverLetter.jobTitle.trim();
    const greeting = `Dear ${recipient},`;
    const signature = resume.fullName.trim() || 'Candidate';

    return [
      greeting,
      '',
      coverLetter.content.trim(),
      '',
      'Sincerely,',
      signature,
      company || role ? '' : undefined,
      company ? `Company: ${company}` : undefined,
      role ? `Role: ${role}` : undefined
    ]
      .filter((line): line is string => line !== undefined)
      .join('\n')
      .trim();
  }

  private buildResumeDocxContent(resume: ProfessionalResume): Paragraph[] {
    const content: Paragraph[] = [];
    const name = resume.fullName.trim() || 'Candidate Name';

    content.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 40 },
        children: [
          new TextRun({
            text: name,
            bold: true,
            size: 36,
            color: this.bodyHex
          })
        ]
      })
    );

    if (resume.headline.trim()) {
      content.push(
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 50 },
          children: [
            new TextRun({
              text: resume.headline.trim(),
              bold: true,
              size: 22,
              color: this.accentHex
            })
          ]
        })
      );
    }

    const contact = this.contactParts(resume);
    if (contact.length > 0) {
      content.push(
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 170 },
          children: [
            new TextRun({
              text: contact.join(' | '),
              size: 18,
              color: this.mutedHex
            })
          ]
        })
      );
    }

    content.push(this.docxSectionHeading('Professional Summary'));
    content.push(
      new Paragraph({
        spacing: { after: 150 },
        children: [new TextRun(resume.summary.trim())]
      })
    );

    const skills = this.cleanStrings(resume.skills);
    if (skills.length > 0) {
      content.push(this.docxSectionHeading('Core Skills'));
      content.push(
        new Paragraph({
          spacing: { after: 150 },
          children: [new TextRun(skills.join(' | '))]
        })
      );
    }

    if (resume.experience.length > 0) {
      content.push(this.docxSectionHeading('Professional Experience'));
      for (const experience of resume.experience) {
        content.push(...this.experienceDocx(experience));
      }
    }

    if (resume.projects.length > 0) {
      content.push(this.docxSectionHeading('Selected Projects'));
      for (const project of resume.projects) {
        content.push(...this.projectDocx(project));
      }
    }

    if (resume.education.length > 0) {
      content.push(this.docxSectionHeading('Education'));
      for (const education of resume.education) {
        content.push(...this.educationDocx(education));
      }
    }

    const certifications = this.cleanStrings(resume.certifications);
    if (certifications.length > 0) {
      content.push(this.docxSectionHeading('Certifications'));
      content.push(
        ...certifications.map(
          (certification) =>
            new Paragraph({
              bullet: { level: 0 },
              spacing: { after: 35 },
              children: [new TextRun(certification)]
            })
        )
      );
    }

    return content;
  }

  private experienceDocx(experience: ResumeExperience): Paragraph[] {
    const dateRange = this.dateRange(experience.startDate, experience.endDate);
    const meta = [experience.location.trim(), dateRange].filter(Boolean).join(' | ');

    return [
      new Paragraph({
        spacing: { before: 70, after: 20 },
        children: [
          new TextRun({ text: experience.jobTitle.trim(), bold: true, size: 21 }),
          ...(experience.company.trim()
            ? [new TextRun({ text: ` | ${experience.company.trim()}`, bold: true, color: this.accentHex })]
            : [])
        ]
      }),
      ...(meta
        ? [
            new Paragraph({
              spacing: { after: 45 },
              children: [new TextRun({ text: meta, italics: true, size: 18, color: this.mutedHex })]
            })
          ]
        : []),
      ...this.cleanStrings(experience.bulletPoints).map(
        (point) =>
          new Paragraph({
            bullet: { level: 0 },
            spacing: { after: 35, line: 230 },
            children: [new TextRun(point)]
          })
      )
    ];
  }

  private projectDocx(project: ResumeProject): Paragraph[] {
    const technologies = this.cleanStrings(project.technologies);
    return [
      new Paragraph({
        spacing: { before: 70, after: 25 },
        children: [new TextRun({ text: project.name.trim(), bold: true, size: 21 })]
      }),
      ...(project.description.trim()
        ? [new Paragraph({ spacing: { after: 25 }, children: [new TextRun(project.description.trim())] })]
        : []),
      ...(technologies.length > 0
        ? [
            new Paragraph({
              spacing: { after: 70 },
              children: [
                new TextRun({ text: 'Technologies: ', bold: true, size: 18, color: this.mutedHex }),
                new TextRun({ text: technologies.join(', '), size: 18, color: this.mutedHex })
              ]
            })
          ]
        : [])
    ];
  }

  private educationDocx(education: ResumeEducation): Paragraph[] {
    const meta = [education.institution, education.location, education.graduationDate]
      .map((value) => value.trim())
      .filter(Boolean)
      .join(' | ');

    return [
      new Paragraph({
        spacing: { before: 60, after: 20 },
        children: [new TextRun({ text: education.degree.trim(), bold: true, size: 21 })]
      }),
      ...(meta
        ? [
            new Paragraph({
              spacing: { after: 35 },
              children: [new TextRun({ text: meta, italics: true, size: 18, color: this.mutedHex })]
            })
          ]
        : []),
      ...this.cleanStrings(education.details).map(
        (detail) =>
          new Paragraph({
            bullet: { level: 0 },
            spacing: { after: 30 },
            children: [new TextRun(detail)]
          })
      )
    ];
  }

  private docxSectionHeading(text: string): Paragraph {
    return new Paragraph({
      spacing: { before: 120, after: 75 },
      border: {
        bottom: {
          style: BorderStyle.SINGLE,
          size: 8,
          color: this.accentHex,
          space: 4
        }
      },
      children: [
        new TextRun({
          text: text.toUpperCase(),
          bold: true,
          size: 20,
          color: this.accentHex,
          characterSpacing: 20
        })
      ]
    });
  }

  private buildCoverLetterDocxContent(
    resume: ProfessionalResume,
    coverLetter: CoverLetterDocument
  ): Paragraph[] {
    const name = resume.fullName.trim() || 'Candidate Name';
    const contact = this.contactParts(resume).join(' | ');
    const recipient = coverLetter.recipient.trim() || 'Hiring Manager';
    const company = coverLetter.companyName.trim();
    const role = coverLetter.jobTitle.trim();
    const paragraphs = this.splitIntoSentences(coverLetter.content);

    return [
      new Paragraph({
        spacing: { after: 45 },
        children: [
          new TextRun({
            text: name,
            bold: true,
            size: 32,
            color: this.bodyHex
          })
        ]
      }),
      ...(contact
        ? [
            new Paragraph({
              spacing: { after: 260 },
              children: [new TextRun({ text: contact, size: 18, color: this.mutedHex })]
            })
          ]
        : []),
      new Paragraph({ text: this.currentDateLong(), spacing: { after: 220 } }),
      new Paragraph({
        spacing: { after: 35 },
        children: [new TextRun({ text: recipient, bold: true })]
      }),
      ...(role ? [new Paragraph({ text: role, spacing: { after: 35 } })] : []),
      ...(company ? [new Paragraph({ text: company, spacing: { after: 220 } })] : []),
      new Paragraph({ text: `Dear ${recipient},`, spacing: { after: 190 } }),
      ...paragraphs.map(
        (paragraph) =>
          new Paragraph({
            text: paragraph,
            spacing: { after: 190, line: 276 }
          })
      ),
      new Paragraph({ text: 'Sincerely,', spacing: { before: 80, after: 180 } }),
      new Paragraph({
        children: [new TextRun({ text: name, bold: true })]
      })
    ];
  }

  private renderResumePdf(pdf: jsPDF, resume: ProfessionalResume): void {
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const marginX = 48;
    const contentWidth = pageWidth - marginX * 2;
    const bottomMargin = 46;
    let y = 48;

    const ensureSpace = (height: number): void => {
      if (y + height > pageHeight - bottomMargin) {
        pdf.addPage();
        y = 48;
      }
    };

    const writeWrapped = (
      text: string,
      fontSize = 9.5,
      lineHeight = 13.2,
      indent = 0,
      style: 'normal' | 'bold' | 'italic' = 'normal',
      color: [number, number, number] = [31, 41, 55]
    ): void => {
      if (!text.trim()) {
        return;
      }

      pdf.setFont('helvetica', style);
      pdf.setFontSize(fontSize);
      pdf.setTextColor(...color);
      const lines = pdf.splitTextToSize(text.trim(), contentWidth - indent) as string[];
      ensureSpace(lines.length * lineHeight + 2);
      pdf.text(lines, marginX + indent, y);
      y += lines.length * lineHeight;
    };

    const section = (title: string): void => {
      ensureSpace(34);
      y += 8;
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(10.5);
      pdf.setTextColor(31, 78, 120);
      pdf.text(title.toUpperCase(), marginX, y);
      y += 5;
      pdf.setDrawColor(31, 78, 120);
      pdf.setLineWidth(0.9);
      pdf.line(marginX, y, pageWidth - marginX, y);
      y += 14;
    };

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(19);
    pdf.setTextColor(31, 41, 55);
    pdf.text(resume.fullName.trim() || 'Candidate Name', pageWidth / 2, y, { align: 'center' });
    y += 18;

    if (resume.headline.trim()) {
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(10.5);
      pdf.setTextColor(31, 78, 120);
      pdf.text(resume.headline.trim(), pageWidth / 2, y, { align: 'center' });
      y += 15;
    }

    const contact = this.contactParts(resume).join(' | ');
    if (contact) {
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(8.5);
      pdf.setTextColor(91, 101, 115);
      const contactLines = pdf.splitTextToSize(contact, contentWidth) as string[];
      pdf.text(contactLines, pageWidth / 2, y, { align: 'center' });
      y += contactLines.length * 11 + 5;
    }

    section('Professional Summary');
    writeWrapped(resume.summary);

    const skills = this.cleanStrings(resume.skills);
    if (skills.length > 0) {
      section('Core Skills');
      writeWrapped(skills.join(' | '));
    }

    if (resume.experience.length > 0) {
      section('Professional Experience');
      for (const experience of resume.experience) {
        ensureSpace(54);
        writeWrapped(
          `${experience.jobTitle}${experience.company ? ` | ${experience.company}` : ''}`,
          10.2,
          13.5,
          0,
          'bold'
        );
        const meta = [experience.location, this.dateRange(experience.startDate, experience.endDate)]
          .map((value) => value.trim())
          .filter(Boolean)
          .join(' | ');
        if (meta) {
          writeWrapped(meta, 8.4, 11.5, 0, 'italic', [91, 101, 115]);
        }
        for (const point of this.cleanStrings(experience.bulletPoints)) {
          writeWrapped(`• ${point}`, 9.3, 12.7, 10);
        }
        y += 4;
      }
    }

    if (resume.projects.length > 0) {
      section('Selected Projects');
      for (const project of resume.projects) {
        writeWrapped(project.name, 10.2, 13.5, 0, 'bold');
        writeWrapped(project.description, 9.3, 12.7);
        const technologies = this.cleanStrings(project.technologies);
        if (technologies.length > 0) {
          writeWrapped(`Technologies: ${technologies.join(', ')}`, 8.5, 11.5, 0, 'italic', [91, 101, 115]);
        }
        y += 4;
      }
    }

    if (resume.education.length > 0) {
      section('Education');
      for (const education of resume.education) {
        writeWrapped(education.degree, 10.2, 13.5, 0, 'bold');
        const meta = [education.institution, education.location, education.graduationDate]
          .map((value) => value.trim())
          .filter(Boolean)
          .join(' | ');
        if (meta) {
          writeWrapped(meta, 8.5, 11.5, 0, 'italic', [91, 101, 115]);
        }
        for (const detail of this.cleanStrings(education.details)) {
          writeWrapped(`• ${detail}`, 9.2, 12.5, 10);
        }
        y += 3;
      }
    }

    const certifications = this.cleanStrings(resume.certifications);
    if (certifications.length > 0) {
      section('Certifications');
      for (const certification of certifications) {
        writeWrapped(`• ${certification}`, 9.3, 12.7, 10);
      }
    }
  }

  private renderCoverLetterPdf(
    pdf: jsPDF,
    resume: ProfessionalResume,
    coverLetter: CoverLetterDocument
  ): void {
    const pageWidth = pdf.internal.pageSize.getWidth();
    const marginX = 58;
    const contentWidth = pageWidth - marginX * 2;
    let y = 60;
    const name = resume.fullName.trim() || 'Candidate Name';
    const recipient = coverLetter.recipient.trim() || 'Hiring Manager';
    const company = coverLetter.companyName.trim();
    const role = coverLetter.jobTitle.trim();

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(18);
    pdf.setTextColor(31, 41, 55);
    pdf.text(name, marginX, y);
    y += 18;

    const contact = this.contactParts(resume).join(' | ');
    if (contact) {
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(8.5);
      pdf.setTextColor(91, 101, 115);
      const lines = pdf.splitTextToSize(contact, contentWidth) as string[];
      pdf.text(lines, marginX, y);
      y += lines.length * 11;
    }

    y += 22;
    pdf.setDrawColor(31, 78, 120);
    pdf.setLineWidth(1.1);
    pdf.line(marginX, y, pageWidth - marginX, y);
    y += 28;

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(10.5);
    pdf.setTextColor(31, 41, 55);
    pdf.text(this.currentDateLong(), marginX, y);
    y += 32;

    pdf.setFont('helvetica', 'bold');
    pdf.text(recipient, marginX, y);
    y += 15;

    pdf.setFont('helvetica', 'normal');
    if (role) {
      pdf.text(role, marginX, y);
      y += 15;
    }
    if (company) {
      pdf.text(company, marginX, y);
      y += 15;
    }

    y += 18;
    pdf.text(`Dear ${recipient},`, marginX, y);
    y += 24;

    for (const paragraph of this.splitIntoSentences(coverLetter.content)) {
      const lines = pdf.splitTextToSize(paragraph, contentWidth) as string[];
      pdf.text(lines, marginX, y);
      y += lines.length * 15 + 14;
    }

    y += 8;
    pdf.text('Sincerely,', marginX, y);
    y += 30;
    pdf.setFont('helvetica', 'bold');
    pdf.text(name, marginX, y);
  }

  private contactParts(resume: ProfessionalResume): string[] {
    return [
      resume.contact.email,
      resume.contact.phone,
      resume.contact.location,
      resume.contact.linkedIn,
      resume.contact.portfolio
    ]
      .map((value) => value.trim())
      .filter(Boolean);
  }

  private dateRange(startDate: string, endDate: string): string {
    const start = startDate.trim();
    const end = endDate.trim();

    if (start && end) {
      return `${start} - ${end}`;
    }

    return start || end;
  }

  private cleanStrings(values: readonly string[]): string[] {
    return values.map((value) => value.trim()).filter(Boolean);
  }

  private splitIntoSentences(content: string): string[] {
    const matches = content.trim().match(/[^.!?]+[.!?]+|[^.!?]+$/g);
    const sentences = (matches ?? [content])
      .map((sentence) => sentence.trim())
      .filter(Boolean);

    return sentences.length > 0 ? sentences : [content.trim()];
  }

  private currentDateLong(): string {
    return new Intl.DateTimeFormat(undefined, {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    }).format(new Date());
  }

  private safeFileName(value: string): string {
    const cleaned = value
      .trim()
      .replace(/[^a-zA-Z0-9-_ ]+/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '');

    return cleaned || 'ResumeForge';
  }

  private downloadBlob(blob: Blob, fileName: string): void {
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = fileName;
    anchor.click();
    URL.revokeObjectURL(url);
  }
}
